services:
  cv-sahulat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv_sahulat
    ports:
      - "8080:8080"
    volumes:
      # Optional: Mount a folder for processed files
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
